# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:59
from __future__ import unicode_literals

import DriverTest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=100, verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u041e\u0434\u0438\u043d')),
                ('answer2', models.CharField(max_length=100, verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u0414\u0432\u0430')),
                ('answer3', models.CharField(max_length=100, verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u0422\u0440\u0438')),
                ('answer4', models.CharField(max_length=100, verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u0427\u0435\u0442\u044b\u0440\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('img', models.ImageField(blank=True, upload_to=DriverTest.models.saving_path, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0443\u0430\u043b\u0435\u043d')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='DriverTest.Answer', verbose_name='\u041e\u0442\u0432\u0435\u0442')),
            ],
        ),
    ]
